create or replace function public.teacher_student_analytics(p_student uuid,p_days int default null)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare result jsonb; cutoff timestamptz:=case when p_days is null then '-infinity'::timestamptz else now()-(p_days||' days')::interval end;
begin
  if not public.is_linked_teacher(p_student) then raise exception 'forbidden'; end if;
  select jsonb_build_object(
    'profile',jsonb_build_object('id',p.id,'first_name',p.first_name,'last_name',p.last_name,'username',p.username,'class_name',p.class_name,'status',p.status,'subject',l.subject,'zoom_url',l.default_zoom_url,'last_activity',p.updated_at),
    'summary',(select jsonb_build_object('assigned',count(*),'completed',count(*) filter(where ha.status in ('submitted','reviewed')),'overdue',count(*) filter(where ha.status not in ('submitted','reviewed') and public.assignment_deadline(ha.id)<now()),'awaiting_review',count(*) filter(where ha.status='awaiting_review'),'reviewed',count(*) filter(where ha.status='reviewed'),'completion_rate',case when count(*)=0 then 0 else round(100.0*count(*) filter(where ha.status in ('submitted','reviewed'))/count(*)) end) from public.homework_assignments ha where ha.student_id=p_student),
    'history',(select coalesce(jsonb_agg(jsonb_build_object('assignment_id',ha.id,'title',v.title,'topic',coalesce(t.name,'Без темы'),'mode',v.mode,'deadline',ha.deadline_at,'effective_deadline',public.assignment_deadline(ha.id),'status',ha.status,'attempts_used',(select count(*) from public.attempts a where a.assignment_id=ha.id),'best_score',(select max(a.score) from public.attempts a where a.assignment_id=ha.id),'automatic_maximum',(select max(a.maximum_score) from public.attempts a where a.assignment_id=ha.id),'submitted_at',(select max(a.submitted_at) from public.attempts a where a.assignment_id=ha.id)) order by ha.deadline_at desc),'[]'::jsonb) from public.homework_assignments ha join public.homework_versions v on v.id=ha.homework_version_id left join public.topics t on t.id=v.topic_id where ha.student_id=p_student and ha.deadline_at>=cutoff),
    'topics',(select coalesce(jsonb_agg(row_to_json(x)),'[]'::jsonb) from (select coalesce(t.name,'Без темы') topic,count(distinct ha.id) completed,count(a.id) attempts,coalesce(round(avg(case when a.maximum_score>0 then 100.0*a.score/a.maximum_score end)),0) average,coalesce(max(case when a.maximum_score>0 then round(100.0*a.score/a.maximum_score) end),0) best from public.homework_assignments ha join public.homework_versions v on v.id=ha.homework_version_id left join public.topics t on t.id=v.topic_id left join public.attempts a on a.assignment_id=ha.id where ha.student_id=p_student and coalesce(a.submitted_at,ha.deadline_at)>=cutoff group by t.name order by t.name)x),
    'attempts',(select coalesce(jsonb_agg(jsonb_build_object('id',a.id,'assignment_id',a.assignment_id,'title',v.title,'attempt_number',a.attempt_number,'score',a.score,'maximum',a.maximum_score,'started_at',a.started_at,'submitted_at',a.submitted_at,'duration_seconds',a.duration_seconds) order by a.submitted_at desc),'[]'::jsonb) from public.attempts a join public.homework_assignments ha on ha.id=a.assignment_id join public.homework_versions v on v.id=ha.homework_version_id where a.student_id=p_student and a.submitted_at>=cutoff)
  ) into result from public.profiles p join public.teacher_student_links l on l.student_id=p.id and l.teacher_id=auth.uid() where p.id=p_student;
  return result;
end $$;
revoke all on function public.teacher_student_analytics(uuid,int) from public;
grant execute on function public.teacher_student_analytics(uuid,int) to authenticated;
