create or replace function public.is_active_user() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and status='active') $$;
create or replace function public.is_linked_teacher(student uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_active_user() and exists(select 1 from public.teacher_student_links where teacher_id=auth.uid() and student_id=student) $$;
create or replace function public.is_org_teacher(org uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_active_user() and exists(select 1 from public.organization_members where organization_id=org and user_id=auth.uid() and role in ('owner','teacher')) $$;
create or replace function public.is_org_owner(org uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_active_user() and exists(select 1 from public.organization_members where organization_id=org and user_id=auth.uid() and role='owner') $$;

drop policy if exists "student upload originals" on storage.objects;
drop policy if exists "participants read originals" on storage.objects;
drop policy if exists "student upload processed" on storage.objects;
drop policy if exists "participants read processed" on storage.objects;
create policy "student upload own originals" on storage.objects for insert to authenticated with check(bucket_id='homework-originals' and public.is_active_user() and split_part(name,'/',3)=auth.uid()::text and exists(select 1 from public.manual_submission_versions sv join public.manual_submissions s on s.id=sv.submission_id where sv.id::text=split_part(name,'/',5) and s.student_id=auth.uid() and s.submitted_at is null));
create policy "participants read own originals" on storage.objects for select to authenticated using(bucket_id='homework-originals' and public.is_active_user() and (split_part(name,'/',3)=auth.uid()::text or (split_part(name,'/',2)=auth.uid()::text and public.is_linked_teacher(split_part(name,'/',3)::uuid))));
create policy "student upload own derivatives" on storage.objects for insert to authenticated with check(bucket_id in ('homework-processed','homework-thumbnails') and public.is_active_user() and split_part(name,'/',3)=auth.uid()::text and exists(select 1 from public.manual_submission_versions sv join public.manual_submissions s on s.id=sv.submission_id where sv.id::text=split_part(name,'/',5) and s.student_id=auth.uid() and s.submitted_at is null));
create policy "participants read own derivatives" on storage.objects for select to authenticated using(bucket_id in ('homework-processed','homework-thumbnails') and public.is_active_user() and (split_part(name,'/',3)=auth.uid()::text or (split_part(name,'/',2)=auth.uid()::text and public.is_linked_teacher(split_part(name,'/',3)::uuid))));
create policy "student deletes draft uploads" on storage.objects for delete to authenticated using(bucket_id in ('homework-originals','homework-processed','homework-thumbnails') and public.is_active_user() and split_part(name,'/',3)=auth.uid()::text and exists(select 1 from public.manual_submission_versions sv join public.manual_submissions s on s.id=sv.submission_id where sv.id::text=split_part(name,'/',5) and s.student_id=auth.uid() and s.submitted_at is null));
